from .ajax_view import AjaxView
from .clases_view import ClasesView
from .consulta_view import ConsultaView
from .cuentas_view import CuentasView
from .form_view import FormView
from .gasto_view import GastoView
from .pagina_ahorros_view import PaginaAhorrosView
from .pagina_index_view import PaginaIndexView
from .resumen_ahorro_view import ResumenAhorroView
from .search_view import SearchView
